## How to make cellData_rgb.tsv
### The original name of his notebook was cellData_rgb.ipynb and was saved at /media/dimitris/New Volume/data/Izzie/221020_IF_primary_then_seq/pciSeq

In [40]:
import pandas as pd
import numpy as np
import json
from PIL import ImageColor

In [41]:
cellData = pd.read_csv(r"E:\data\Izzie\221020_IF_primary_then_seq\pciSeq\cellData.tsv", sep='\t')

cellData['Genenames'] = cellData['Genenames'].apply(lambda x: eval(x))
cellData['CellGeneCount'] = cellData['CellGeneCount'].apply(lambda x: eval(x))
cellData['ClassName'] = cellData['ClassName'].apply(lambda x: eval(x))
cellData['Prob'] = cellData['Prob'].apply(lambda x: eval(x))
cellData['ellipsoid_border'] = cellData['ellipsoid_border'].apply(lambda x: eval(x))
cellData['sphere_scale'] = cellData['sphere_scale'].apply(lambda x: eval(x))
cellData['sphere_rotation'] = cellData['sphere_rotation'].apply(lambda x: eval(x))

In [42]:
cellData.head()

,Cell_Num,X,Y,Z,X_0,Y_0,Genenames,CellGeneCount,ClassName,Prob,rho,sigma_x,sigma_y,ellipsoid_border,sphere_position,sphere_scale,sphere_rotation,cov
0,1,6165.810962,2339.832385,33.411673,6170.967139,2341.979059,"[Aldoc, Cplx2, Cryab, Cxcl14, Enpp2, Gabrd, Id...","[1.1654906453405733, 5.732468101199288, 1.8107...","[Astro.1, Astro.3, Astro.4]","[0.9651327791386975, 0.01799016441234252, 0.01...",0.045855,8.813552,9.410527,"[[6174, 2366, 38], [6178, 2362, 45], [6182, 23...",NaN,"[28.511789440520793, 26.264880800603784, 25.21...","[-0.11098321011220165, -0.21211068183587992, 1...","[77.67869821624174, 3.803221027253063, 1.95121..."
1,2,6361.068962,2386.612458,44.156584,6331.993498,2347.514891,"[Bcl11b, Cplx2, Cryab, Pcp4, Slc6a1]","[3.8445276033681077, 0.9678544416238882, 0.914...","[Astro.1, Astro.3, Endo, PC.CA1.1, Vsmc, Zero]","[0.2141665780058545, 0.007655196633820753, 0.0...",0.006667,8.674838,9.136063,"[[6338, 2394, 33], [6342, 2403, 33], [6347, 24...",NaN,"[28.126805921056697, 26.008549598074516, 26.25...","[-0.6652369838729317, -0.2345625184908082, -1....","[75.25281320985701, 0.5284159383989598, -1.130..."
2,3,7447.276375,2372.895546,43.243794,7441.553126,2380.255953,"[Cox6a2, Cplx2, Cxcl14, Enpp2, Id2, Kctd12, Pc...","[0.8429367942893861, 0.9196706804331437, 0.906...","[Astro.1, Astro.3, Endo, Eryth.1, Eryth.2, Mic...","[0.12870571985774965, 0.0015045954490045118, 0...",-0.038704,8.902847,8.821511,"[[7426, 2386, 54], [7428, 2381, 61], [7431, 23...",NaN,"[25.9456263339308, 26.533202320814468, 26.7085...","[0.0, 1.5707963267948966, 0.0]","[79.26068611248698, -3.039691519228941, -3.869..."
3,4,6900.054811,2352.915336,37.525268,6894.990383,2357.403255,"[Cck, Cryab, Cxcl14, Enpp2, Kctd12, Neurod6, N...","[1.8895535121886537, 0.0407443165425208, 1.898...","[Astro.1, Astro.3, Astro.4, Endo, Eryth.1, Ery...","[0.24668174618385882, 0.012781997148599818, 0....",-0.060226,9.161811,8.625767,"[[6924, 2342, 30], [6921, 2334, 31], [6916, 23...",NaN,"[25.40866165347804, 26.113796675933074, 27.485...","[0.0, 1.5707963267948966, 0.0]","[83.93877661376476, -4.759496206213277, -3.390..."
4,5,7658.489237,2386.655934,53.946058,7662.025681,2391.198519,"[Cadps2, Cryab, Cxcl14, Enpp2, Nrn1, Pde1a, Pe...","[0.03847201494604884, 0.05970429469520792, 0.1...","[Endo, Microglia.1, Vsmc, Zero]","[0.007131000757635192, 0.0037597586709261182, ...",-0.001716,8.859052,8.880222,"[[7665, 2379, 78], [7659, 2385, 81], [7653, 23...",NaN,"[26.5536336186615, 26.841037877499396, 26.6406...","[1.5707963267948966, 0.0, -2.8522023549044375]","[78.48279399040419, -0.13498575340978305, 0.46..."

In [43]:
cellData['BestClass'] = cellData.apply(lambda r: r['ClassName'][np.argmax(r['Prob'])], axis=1)
cellData['BestProb'] = cellData.apply(lambda r: np.max(r['Prob']), axis=1)

In [44]:
cellData = cellData[['Cell_Num', 'X','Y','Z','ClassName','Prob','sphere_scale', 'sphere_rotation', 'BestClass']] 
cellData.head()

,Cell_Num,X,Y,Z,ClassName,Prob,sphere_scale,sphere_rotation,BestClass
0,1,6165.810962,2339.832385,33.411673,"[Astro.1, Astro.3, Astro.4]","[0.9651327791386975, 0.01799016441234252, 0.01...","[28.511789440520793, 26.264880800603784, 25.21...","[-0.11098321011220165, -0.21211068183587992, 1...",Astro.1
1,2,6361.068962,2386.612458,44.156584,"[Astro.1, Astro.3, Endo, PC.CA1.1, Vsmc, Zero]","[0.2141665780058545, 0.007655196633820753, 0.0...","[28.126805921056697, 26.008549598074516, 26.25...","[-0.6652369838729317, -0.2345625184908082, -1....",PC.CA1.1
2,3,7447.276375,2372.895546,43.243794,"[Astro.1, Astro.3, Endo, Eryth.1, Eryth.2, Mic...","[0.12870571985774965, 0.0015045954490045118, 0...","[25.9456263339308, 26.533202320814468, 26.7085...","[0.0, 1.5707963267948966, 0.0]",Vsmc
3,4,6900.054811,2352.915336,37.525268,"[Astro.1, Astro.3, Astro.4, Endo, Eryth.1, Ery...","[0.24668174618385882, 0.012781997148599818, 0....","[25.40866165347804, 26.113796675933074, 27.485...","[0.0, 1.5707963267948966, 0.0]",PC.CA1.1
4,5,7658.489237,2386.655934,53.946058,"[Endo, Microglia.1, Vsmc, Zero]","[0.007131000757635192, 0.0037597586709261182, ...","[26.5536336186615, 26.841037877499396, 26.6406...","[1.5707963267948966, 0.0, -2.8522023549044375]",Zero

In [45]:
f = open(r'E:\data\Izzie\221020_IF_primary_then_seq\pciSeq\classColours.json')
data = json.load(f)

In [46]:
classColours = pd.DataFrame(data)
classColours.sort_values('className')

         className IdentifiedType    color
39         Astro.1     Non Neuron  #FFFFFF
40         Astro.2     Non Neuron  #FFFFFF
41         Astro.3     Non Neuron  #FFFFFF
42         Astro.4     Non Neuron  #FFFFFF
43         Astro.5     Non Neuron  #FFFFFF
..             ...            ...      ...
58  Sst.Pnoc.Pvalb           O/LM  #008FCC
31   Vip.Crh.C1ql1            IS2  #FAE52E
32    Vip.Crh.Pcp4            IS2  #FAE52E
55            Vsmc     Non Neuron  #FFFFFF
71            Zero           Zero  #000000

[72 rows x 3 columns]

In [47]:
uname, id = np.unique(classColours.IdentifiedType, return_inverse=True)

In [48]:
classColours['class_id'] = id
classColours

            className     IdentifiedType    color  class_id
0   Pvalb.C1ql1.Cpne5         Axo-axonic  #3A19BD         0
1     Pvalb.C1ql1.Npy         Axo-axonic  #3A19BD         0
2   Pvalb.C1ql1.Pvalb         Axo-axonic  #3A19BD         0
3            Sst.Nos1     Backprojection  #3DCCFF         1
4    Pvalb.Tac1.Nr4a2             Basket  #7757FA         2
..                ...                ...      ...       ...
67        Ntng1.Rgs10  Radiatum retrohip  #3D855A        23
68        Ntng1.Synpr  Radiatum retrohip  #3D855A        23
69        Ntng1.Chrm2         Trilaminar  #1F663B        24
70          Sst.Cryab       Unidentified  #A6A6A6        25
71               Zero               Zero  #000000        26

[72 rows x 4 columns]

In [49]:
# use this to make the json for the classCOnfig.js file. You migh have to manually 
# change strings like "class_id":0 to "class_id":"class_0" and maybe use this as the className key
classColours.to_json('classConfig2.js', orient='records')

In [50]:
r,g,b = list(zip(*classColours.color.apply(lambda d: ImageColor.getcolor(d, "RGB")).values))

In [51]:
classColours['r'] = r
classColours['g'] = g
classColours['b'] = b
classColours

            className     IdentifiedType    color  class_id    r    g    b
0   Pvalb.C1ql1.Cpne5         Axo-axonic  #3A19BD         0   58   25  189
1     Pvalb.C1ql1.Npy         Axo-axonic  #3A19BD         0   58   25  189
2   Pvalb.C1ql1.Pvalb         Axo-axonic  #3A19BD         0   58   25  189
3            Sst.Nos1     Backprojection  #3DCCFF         1   61  204  255
4    Pvalb.Tac1.Nr4a2             Basket  #7757FA         2  119   87  250
..                ...                ...      ...       ...  ...  ...  ...
67        Ntng1.Rgs10  Radiatum retrohip  #3D855A        23   61  133   90
68        Ntng1.Synpr  Radiatum retrohip  #3D855A        23   61  133   90
69        Ntng1.Chrm2         Trilaminar  #1F663B        24   31  102   59
70          Sst.Cryab       Unidentified  #A6A6A6        25  166  166  166
71               Zero               Zero  #000000        26    0    0    0

[72 rows x 7 columns]

In [52]:
uname, id = np.unique(classColours.className, return_inverse=True)

In [53]:
mydict = {}
mydict.update(zip(classColours.className, classColours.class_id))

In [54]:
classes = cellData.ClassName.apply(lambda d: [mydict[v] for v in d])

In [55]:
cellData['classes'] = classes
cellData.shape

(44108, 10)

In [56]:
cellData = cellData.merge(classColours, left_on='BestClass', right_on='className')
cellData.shape

(44108, 17)

In [57]:
cellData = cellData[['Cell_Num', 'X','Y','Z','classes','Prob', 'sphere_scale', 'sphere_rotation', 'r', 'g', 'b']]

In [58]:
cellData = cellData.rename(columns={"Cell_Num": "label", 
                                    "X": "x",
                                    "Y": "y",
                                    "Z": "z",
                                    "Prob": "class_prob"})

In [59]:
cellData = cellData[["label", "x", "y", "z", "classes", "class_prob", "sphere_scale", "sphere_rotation", "r", "g", "b"]]
cellData.x = cellData.x - 3893.48 # substract the spots.x.mean()
cellData.y = cellData.y - 4150.75 # substract the spots.y.mean()
cellData.z = cellData.z - 96.79   # substract the spots.z.mean()

In [61]:
cellData.to_csv("cellData_rgb.tsv", sep='\t', index=False)

In [60]:
cellData

,label,x,y,z,classes,class_prob,sphere_scale,sphere_rotation,r,g,b
0,1,2272.330962,-1810.917615,-63.378327,"[17, 17, 17]","[0.9651327791386975, 0.01799016441234252, 0.01...","[28.511789440520793, 26.264880800603784, 25.21...","[-0.11098321011220165, -0.21211068183587992, 1...",255,255,255
1,9,2338.094878,-1739.473268,-61.895388,"[17, 17, 17, 11, 17, 20, 17]","[0.8617024488835708, 0.10604515024031035, 0.00...","[31.100308574716554, 26.786457765010006, 25.37...","[-0.07140962498711191, 0.049216504573033185, -...",255,255,255
2,13,2984.190224,-1707.651911,-54.921996,"[17, 17, 17, 17]","[0.799284271439622, 0.0018361826268794693, 0.1...","[28.041126178234975, 24.81154941045717, 29.536...","[1.5707963267948966, 0.0, -0.12635702392284134]",255,255,255
3,23,2783.135695,-1622.527213,-56.434863,"[17, 17, 17, 17]","[0.7785657652536366, 0.002730199724513174, 0.1...","[25.18957180340717, 28.684621144600996, 26.802...","[0.0, 1.5707963267948966, 0.0]",255,255,255
4,24,3388.586140,-1623.423638,-57.005935,"[17, 17, 17]","[0.5527831683012111, 0.2582301145466959, 0.188...","[24.942128638302307, 26.057197483966952, 27.71...","[-1.570887968531355, -0.0014105689679747289, 1...",255,255,255
...,...,...,...,...,...,...,...,...,...,...,...
44103,14167,-3492.092802,-1650.176032,-42.950045,"[6, 9]","[0.008626544164841866, 0.9913611225482861]","[31.19560817768418, 26.36100040924149, 31.1171...","[1.5707963267948966, 0.0, -0.18566839860389744]",255,0,0
44104,31006,889.467551,979.953279,27.586347,"[6, 9]","[0.005154919485670307, 0.9940230497245013]","[32.449213086553044, 24.918460199961167, 28.08...","[-1.7900587122233624, 0.013256926894707859, 0....",255,0,0
44105,36593,-2713.751837,59.867808,51.417365,"[6, 9]","[0.008952768399353593, 0.9903261074888051]","[35.31906421091534, 27.0909342558627, 30.24753...","[-1.0165306167864332, -0.6266585115102553, -2....",255,0,0
44106,40397,-2010.486847,-288.456356,42.451911,"[6, 9]","[0.013842763896293343, 0.9861525605316892]","[25.691761158279704, 31.20666319259073, 29.848...","[0.0, 1.5707963267948966, 0.0]",255,0,0
44107,42655,-2745.230399,42.751972,39.502478,[9],[0.999839808074737],"[26.32721616422451, 34.65038702477261, 30.8005...","[-1.0113928783939858, 0.3695084528794277, -0.9...",255,0,0

      className IdentifiedType    color  class_id    r    g    b
39      Astro.1     Non Neuron  #FFFFFF        17  255  255  255
40      Astro.2     Non Neuron  #FFFFFF        17  255  255  255
41      Astro.3     Non Neuron  #FFFFFF        17  255  255  255
42      Astro.4     Non Neuron  #FFFFFF        17  255  255  255
43      Astro.5     Non Neuron  #FFFFFF        17  255  255  255
44      Choroid     Non Neuron  #FFFFFF        17  255  255  255
45         Endo     Non Neuron  #FFFFFF        17  255  255  255
46      Eryth.1     Non Neuron  #FFFFFF        17  255  255  255
47      Eryth.2     Non Neuron  #FFFFFF        17  255  255  255
48  Microglia.1     Non Neuron  #FFFFFF        17  255  255  255
49  Microglia.2     Non Neuron  #FFFFFF        17  255  255  255
50      Oligo.1     Non Neuron  #FFFFFF        17  255  255  255
51      Oligo.2     Non Neuron  #FFFFFF        17  255  255  255
52      Oligo.3     Non Neuron  #FFFFFF        17  255  255  255
53      Oligo.4     Non Neuron  #FFFFFF        17  255  255  255
54      Oligo.5     Non Neuron  #FFFFFF        17  255  255  255
55         Vsmc     Non Neuron  #FFFFFF        17  255  255  255